SAMPLES_ALL = ["OCI_AML2_WT","OCI_AML2_C9", "OCI_AML3_WT"]

resolutions = ["7500", "15000", "30000", "60000", "120000"]

sigma_zeroes = ["0.1", "0.2", "0.4", "0.8", "1.6"]

rule all:
	input:
		expand("{sample}_{res}_{sz}_mustache_loops.tsv", sample = SAMPLES_ALL, res = resolutions, sz = sigma_zeroes),
		expand("clodius/{sz}/{sample}_{res}.combo.multires", sample = SAMPLES_ALL, res = resolutions, sz = sigma_zeroes)

rule call_loops:
	input:
		"/mnt/data/pairtools_run/cooler_files/{sample}_balanced.mcool"
	output:
		"{sample}_{res}_{sz}_mustache_loops.tsv"
	shell:
		"python3 /mnt/data/pairtools_run/mustache_loops/mustache/mustache/mustache.py -f {input} "
		"-r {wildcards.res} "
		"-pt 0.05 " 
		"-sz {wildcards.sz} "
		"-o {output}" 

rule all_combined: 
    input: 
        rules.call_loops.output 
    output:
        "clodius/{sz}/{sample}.combo.multires" 
    shell:
        "clodius aggregate bedpe "
        "--assembly hg38 "
        "--has-header "
        "--chr1-col 1 --from1-col 2 --to1-col 3 "
        "--chr2-col 4 --from2-col 5 --to2-col 6 "
        "--output-file {output} "
        "{input} "
